<script type="text/javascript">
<!-- 
$( document ).ready(function() {

	$('.trie').live('click',function() {

		var tri = $(this).attr('title');
		var tri1 = $(this).attr('title');
		var theme = <?php echo $this->theme->id; ?>;
		var result = tri.indexOf('2');
		
		if(result > -1){
			tri = tri.split('_');
			$(this).attr('title',tri[0]);
			$(this).css('color','rgb(255, 0, 0)');//red
			$(this).nextAll().css('color','white');
			$(this).prevAll().css('color','white');
		}else{
			$(this).attr('title',tri+'_2');
			$(this).css('color','rgb(27, 255, 27)');//green
			$(this).nextAll().css('color','white');
			$(this).prevAll().css('color','white');
		}

		$.ajax({
			url : '<?php echo $this->baseUrl('ajax/filtrer');?>',
			type : 'post',
			data : {
				id_theme : theme,
				tri : tri1
			},
			success:function(data){
				
				 $( "#theme-chroniques" ).html(data);
				    
			},
			error:function(xhr, desc, err){alert(xhr);}
	    }); 
		
	});


	$(function(){
  	    $('.box_skitter_small').skitter({
	  	    height_label: '25px',
	  	  	numbers: false,
	  	  	interval: 2500,
	  	  	animation: 'cubeStopRandom',

	  	 });
  	});

});
-->
</script>
<?php $z=0; foreach($this->chroniques as $c){$z++;}?>
<div id="top-wrapper"></div>
<div id="wrapper" class="theme"> <div>
	
	<div id="theme-content">
		<H2 class="theme"><?php echo $this->theme->libele; ?></H2>
		
		<div id="theme-nav"><p><span class="trie" title="Date">Date</span> - <span class="trie" title="Vue">Vue</span> - <span class="trie" title="Note">Note</span> - <span class="trie" title="Comm">Comm</span></p>  FILTRER : <span class="c"><?php echo $z; ?> chroniques</span></div>
		
		<div id="theme-chroniques">
		<?php 
		
			foreach($this->chroniques as $c) {
				
				echo '
	              		<div class="index-chro theme-chro">
							<div><img alt="dernière chroniques" src="'.$this->baseUrl('images/chroniques/'.$c->num.'.jpg').'" /></div>
							<div class="index-chro-right theme-right">
								<p class="chro-title theme-chro-title">'.$c->titre.'</p>
								<p class="chro-theme">'.$c->theme.'</p>
								<p class="chro-text">'.substr($c->texte,0,320).'</p>
								<p class="chro-comm">'.$c->commentaires.' Commentaires</p>
								<a href="'.$this->baseUrl('index/chronique/id/'.$c->num).'" title="'.$c->titre.'" class="lire-chronique">Lire la chronique</a>
								<div class="theme-note" class="article_'.$c->num.'">';
									for($z=1;$z<6;$z++){ echo  '<img src="'.$this->baseUrl('img/general/star_empty.png').'" width="17" alt="star" class="star_'.$z.'" />'; }
				 echo          '</div>
							</div>
						</div><!-- end index-chro --> ';
				
			}
			
			echo $this->paginationControl($this->chroniques, 'Sliding');
		?>
		</div><!-- end theme-chroniques-->
	</div><!-- end theme-content-->
	<div id="index-side">
		
			<div id="index-connexion">
				<p class="bleu acenter index-side-title">CONNEXION</p>
				<div id="div-conn"><?php echo $this->connexion; ?></div>
				<p class="bleu acenter index-insc-title index-side-title">PAS ENCORE INSCRIT ?</p>
				<p class="bleu f11" style=" width:225px; margin: 0 auto; text-align: center;">rejoignez-nous dès maintenant afin de profiter au maximum des chroniques</p>
				<p class="btn-inscription"><a href="<?php echo $this->baseUrl('index/inscription'); ?>" title="inscription chronque time"></a></p>
			</div><!-- end index-connexion-->
		
			<div id="index-theme">
				<p class="bleu acenter index-side-title">THÈMES</p>
				<?php 
				foreach ($this->random_themes as $th) { ?>
					<button><a href="<?php echo $this->baseUrl('index/theme/id/'.$th->id); ?>" title="<?php echo $th->libele; ?>"><?php echo $th->libele; ?></a></button>
				<?php 
				}	?>
			</div><!-- end index-theme-->
		
			<div id="index-fb">
				<iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fpages%2FChronique-Time%2F520012011364663&amp;width=250&amp;height=258&amp;show_faces=true&amp;colorscheme=light&amp;stream=false&amp;border_color=white&amp;header=false&amp;appId=151983048230591" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:250px; height:258px;" allowTransparency="true"></iframe>
			</div><!-- end index-fb-->
			
			<div id="index-conseil" class="theme-reco">
				<img alt="Conseil des internautes" src="<?php echo $this->baseUrl('img/index/conseil.png');?>" />
				<div class="box_skitter box_skitter_small">
	
				    <ul>  <?php 
				    		
				    	foreach ($this->reco as $c) {	?>
				    		
				        <li>
				        	<p class="rose acenter"><?php echo $c->login; ?> vous recommande</p>
				            <a href="<?php echo $this->baseUrl('index/chronique/id/'.$c->id); ?>"><img alt="<?php echo $c->titre; ?>" class="img-conseil block" src="<?php echo $this->baseUrl('images/chroniques/'.$c->id.'.jpg');?>" /></a>
							<p class="bleu acenter italic"><?php echo $c->titre; ?></p>
							<p class="rose acenter italic" style="margin:0;"><?php echo $c->vue; ?> vues</p>
				            <div class="label_text">
				                <p><?php echo $c->titre; ?></p>
				            </div>
				        </li>  
				        		<?php 
				        } 		?>
				        
				    </ul>
				
				</div>
			</div><!-- end index-conseil-->
		</div>

	</div><!-- end wrapper->div -->
</div><!-- end wrapper -->