<!--
Voir http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->

<?php if ($this->pageCount): ?>
<div class="paginationControl">
	
	<!-- Previous page link -->
	<?php if (isset($this->first)): ?>
	  <a href="<?php echo $this->url(array('page' => $this->first)); ?>" class="prev">prec</a> 
	<?php else: ?>
	  <span class="disabled prev"> </span> 
	<?php endif; ?>
	
	
	<!-- Numbered page links -->
	<?php foreach ($this->pagesInRange as $page): ?>
		  <?php if ($page != $this->current): ?>
		    <a href="<?php echo $this->url(array('page' => $page)); ?>" class="num"><?php echo $page; ?></a> 
		  <?php else: ?>
		    <a href=""  class="num disabled active"><?php echo $page; ?></a> 
		  <?php endif; ?>
	<?php endforeach; ?>
	
	
	<!-- Next page link -->
	<?php if (isset($this->last)): ?>
	  <a href="<?php echo $this->url(array('page' => $this->last)); ?>" class="next">suiv</a>
	<?php else: ?>
	  <span class="disabled next"></span>
	<?php endif; ?>
	
</div>
<?php endif; ?>