 
 <div class="none" id="ChDl" title="Suppression Réussie"><br/>
   <p style="margin:0; text-align:center;">La chronique a été définitivement supprimée !</p>
 </div>
 
 <div class="none" id="PgDl" title="Suppression Réussie"><br/>
   <p style="margin:0; text-align:center;">La page a été définitivement supprimée !</p>
 </div>
 
 <div class="none" id="ThDl" title="Suppression Réussie"><br/>
   <p style="margin:0; text-align:center;">Le thème a été définitivement supprimé !</p>
 </div>
 
 <div class="none" id="CoDl" title="Suppression Réussie"><br/>
   <p style="margin:0; text-align:center;">Le commentaire a été définitivement supprimé !</p>
 </div>
 
 <div class="none" id="UsDl" title="Suppression Réussie"><br/>
   <p style="margin:0; text-align:center;">L'utilisateur a été définitivement supprimé !</p>
 </div>