<br/>
<script type="text/javascript">
<!-- 
$( document ).ready(function() {
	
	//Details chroniques   
	$(".element").live('click',function(){
	
		var theme = $('.ch-theme',this).html();
		var visites = $('.ch-visites',this).html();
		var pages = $('.ch-pages',this).html();
		var commentaires = $('.ch-commentaires',this).html();
		var note = $('.ch-note',this).html();
		var abus = $('.ch-abus',this).html();
	
		$(this).popover({
	
			animation : true,
			placement : 'top',
			trigger   : 'click',
			html	  : true,
			title	  : 'Info Chronique :',
			content : '<strong>Thème</strong> : '+theme+' <br/><strong>Visites</strong> : '+visites+' <br/><strong>Pages</strong> : '+pages+'<br/> <strong>Commentaires</strong> : '+commentaires+' <br/><strong>Note</strong> : '+note+'étoiles <br/> <strong>Abus</strong> : '+abus+'',
			delay : { show: 500, hide: 100 }
		 
		});
		$(this).popover('show');
		
	});
	
	
	//Iframe aperçu
	$(".iframe").live('click',function() {
	
	   $( "#iframe" ).dialog({
	      resizable: false,
	      width: 1000,
	      height:850,
	      modal: true,
	      buttons: {  Annuler: function() { $( this ).dialog( "close" ); }  }
	   });
	   $('.ui-dialog-buttons .ui-dialog-buttonpane button').attr('class','btn');
	   
	});
	
	//Msg de confirmation de suppression
	$(".suppr").live('click',function() {
	
	   var clas = $(this).attr('class').split(' ');
	   var info = $(this).attr('alt').split('&&');
	   var type = clas['0'];
	   var name = info['0'];
	   var id = info['1'];
	   var x = type+'/id/'+id;
	
	   $('#ThDl .supp-txt').html('"'+name+'"');
	   $( "#ThDl" ).dialog({
	      resizable: false,
	      width: 360,
	      height:200,
	      modal: true,
	      buttons: {  
		      Supprimer: function() { window.location.replace("<?php echo $this->baseUrl('admin/del/cat/');?>"+x);  } ,
		      Annuler: function() { $( this ).dialog( "close" ); } 
	      }
	   });
	   $('.ui-dialog-buttons .ui-dialog-buttonpane button').attr('class','btn');
	   
	});
	
	//Msg de confirmation de diffusion
	$(".diff-ch").live('click',function() {
	
	   var clas = $(this).attr('class').split(' ');
	   var info = $(this).attr('alt').split('&&');
	   var valid = info['0'];
	   var name = info['1'];
	   var id = info['2'];
	   var x = 'ch/id/'+id+'/vl/'+valid;
	
	   $('#PgDf .diff-txt').html('"'+name+'"');
	   $( "#PgDf" ).dialog({
	      resizable: false,
	      width: 360,
	      height:200,
	      modal: true,
	      buttons: {  
		      Permuter: function() { window.location.replace("<?php echo $this->baseUrl('admin/diff/cat/');?>"+x);  } , 
		      Annuler: function() { $( this ).dialog( "close" ); }  
	      }
	   });
	   $('.ui-dialog-buttons .ui-dialog-buttonpane button').attr('class','btn');
	   
	});
	

	//Form de recherche
	$("#Rchc").live('click',function() {

	   $( "#ChRc" ).dialog({
	      resizable: false,
	      width: 360,
	      height:250,
	      modal: true,
	   });
	   $('.ui-dialog-buttons .ui-dialog-buttonpane button').attr('class','btn');
	   
	});
	$("#Rchp").live('click',function() {

	   $( "#PgRc" ).dialog({
	      resizable: false,
	      width: 360,
	      height:250,
	      modal: true,
	   });
	   $('.ui-dialog-buttons .ui-dialog-buttonpane button').attr('class','btn');
	   
	});
	$("#Rcht").live('click',function() {

	   $( "#ThRc" ).dialog({
	      resizable: false,
	      width: 360,
	      height:250,
	      modal: true,
	   });
	   $('.ui-dialog-buttons .ui-dialog-buttonpane button').attr('class','btn');
	   
	});
	$("#Rchk").live('click',function() {

	   $( "#ChRk" ).dialog({
	      resizable: false,
	      width: 360,
	      height:270,
	      modal: true,
	      buttons: {  
		      Annuler: function() { $( this ).dialog( "close" ); }  
	      }
	   });
	   $('.ui-dialog-buttons .ui-dialog-buttonpane button').attr('class','btn');
	   
	});
	$("#Rchl").live('click',function() {

	   $( "#LcRc" ).dialog({
	      resizable: false,
	      width: 360,
	      height:270,
	      modal: true,
	      buttons: {  
		      Annuler: function() { $( this ).dialog( "close" ); }  
	      }
	   });
	   $('.ui-dialog-buttons .ui-dialog-buttonpane button').attr('class','btn');
	   
	});

	
	
});	
//--> 
</script>

<div id="wrapper">
 	<div class="bs-docs-example" style="margin-top: -49Px;">
         <ul id="myTab" class="nav nav-tabs">
            <li>  
            	<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-search"></i>&nbsp;&nbsp; Recherches &nbsp; <b class="caret"></b></a>
                <ul class="dropdown-menu" style="top: 7px; width:184px;">
                  <li><a href="#dropdown1" data-toggle="tab" id="Rchc">&nbsp;&nbsp;&nbsp;Chroniques</a></li>
                  <li><a href="#dropdown2" data-toggle="tab" id="Rchp">&nbsp;&nbsp;&nbsp;Pages</a></li>
                  <li><a href="#dropdown2" data-toggle="tab" id="Rcht">&nbsp;&nbsp;&nbsp;Thèmes</a></li>
                  <li><a href="#" data-toggle="tab" id="Rchk">&nbsp;&nbsp;&nbsp;Chroniqueur</a></li>
                  <li><a href="#" data-toggle="tab" id="Rchl">&nbsp;&nbsp;&nbsp;Lecteur</a></li>
                </ul>
         	</li> 
         </ul>
       </div>
       
	<?php if($this->type == "chronique") { ?>
	
              <!--RESULTAT CHRONIQUES -->
              <div class="tab-pane fade in active" id="chroniques">&nbsp;
              	<table class="table table-striped">
              		<tr>
              			<th>N°</th>
              			<th>Titre</th>
              			<th>Chroniqueur</th>
              			<th>Création le</th>
              			<th>Détails</th>
              			<th>Diffusion</th>
              			<th>Actions</th>
              		</tr>
              		<?php 
              			foreach ($this->search as $c) {
				
							echo'<tr>
		  							<td>'.$c->num.'</td>
		  							<td>'.$c->titre.'</td>
		  							<td>'.$c->chroniqueur.'</td>
		  							<td>'.$c->date.'</td>
		  							<td class="element purple pointer">+ de détails...<span class="none ch-pages">'.$c->pages.'</span><span class="none ch-commentaires">'.$c->commentaires.'</span><span class="none ch-theme">'.$c->theme.'</span><span class="none ch-note">'.$c->note.'</span><span class="none ch-abus">'.$c->abus.'</span><span class="none ch-visites">'.$c->visites.'</span></td>
		  							<td>'.($c->valid == 1 ? "<span class='label label-success'>&nbsp;En-Ligne&nbsp;</span>" : "<span class='label label-important'>&nbsp;Hors-Ligne&nbsp;</span>").'</td>
		  							<td>
										<div class="btn-group">
										  <a class="btn btn-primary" data-toggle="dropdown" href="#"><i class="icon-wrench icon-white"></i> Action</a>
										  <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
										  <ul class="dropdown-menu">
										    <li><a href="'.$this->baseUrl('admin/edit/idc/'.$c->num).'" class="ch-modif" id="'.$c->num.'_id" title="'.$c->titre.'"><i class="icon-edit"></i> &nbsp;Modifier</a></li>
										    <li><a href="#" class="supp-ch suppr" alt="'.$c->titre.'&&'.$c->num.'"><i class="icon-trash"></i> &nbsp;Effacer</a></li>
										    <li><a href="#" class="diff-ch" alt="'.$c->valid.'&&'.$c->titre.'&&'.$c->num.'"><i class="icon-ban-circle"></i> &nbsp;Diffusion</a></li>
										    <li class="divider"></li>
										    <li><a href="#" class="iframe"><i class="i icon-eye-open"></i> &nbsp;Visualiser</a></li>
										  </ul>
										</div>
									</td>
								</tr>
	  						';
						}
              		?>
              	</table>
              </div>
              
    <?php }elseif ($this->type == "page") { ?> 
         
              <!-- RESULTAT PAGES -->
				<div class="tab-pane fade in active" id="pages">&nbsp;
              	<table class="table table-striped" width="1022">
              		<caption><i>La Recherche de Pages</i></caption>
              		<tr>
              			<th>Chronique</th>
              			<th>Page</th>
              			<th>Chroniqueur</th>
              			<th>Commentaires</th>
              			<th>Actions</th>
              		</tr>
              		<?php 
              			foreach ($this->search as $p) {

              				// $p->page2 => $p->commentaires
							echo'<tr>
		  							<td>'.$p->titre.'</td>
		  							<td>'.$p->numero.'</td>
		  							<td>'.$p->chroniqueur.'</td>
		  							<td>'.$p->page.'</td>
		  							<td>
										<div class="btn-group">
										  <a class="btn btn-primary" data-toggle="dropdown" href="#"><i class="icon-wrench icon-white"></i> Action</a>
										  <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
										  <ul class="dropdown-menu">
										    <li><a href="'.$this->baseUrl('admin/edit/idp/'.$p->page).'"><i class="icon-pencil"></i>  &nbsp;Editer</a></li>
										    <li><a href="#" class="supp-pg suppr" title="'.$p->titre.$p->page.'&&'.$p->page.'"><i class="icon-trash"></i> &nbsp;Effacer</a></li>
										    <li class="divider"></li>
										    <li><a href="#"><i class="i icon-eye-open"></i>  &nbsp;Chronique</a></li>
										  </ul>
										</div>
									</td>
								</tr>
	  						';

						}
              		?>
              	</table>
              </div>
              
    <?php }elseif ($this->type == "theme") { ?> 
         
              <!-- RESULTAT THEMES -->
              <div class="tab-pane fade in active" id="themes">&nbsp;
              	<table class="table table-striped" style="width:450px;margin:0 auto;">
              		<tr>
              			<th style="width:30px;">N°</th>
              			<th style="width:270px;text-align:center;">Thème</th>
              			<th>Actions</th>
              		</tr>
              		<?php 
              			foreach ($this->search as $t) {
				
							echo'<tr>
		  							<td>'.$t->id.'</td>
		  							<td style="text-align:center;">'.$t->libele.'</td>
		  							<td>
										<div class="btn-group">
										  <a class="btn btn-primary" data-toggle="dropdown" href="#"><i class="icon-wrench icon-white"></i> Action</a>
										  <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
										  <ul class="dropdown-menu">
										    <li><a href="'.$this->baseUrl('admin/edit/idt/'.$t->id).'"><i class="icon-pencil"></i> Editer</a></li>
										    <li><a href="#" class="supp-th suppr" alt="'.$t->libele.'&&'.$t->id.'"><i class="icon-trash"></i> Effacer</a></li>
										  </ul>
										</div>
									</td>
								</tr>
	  						';
						}
              		?>
              	</table>
              	<br />
              </div>

	<?php }elseif ($this->type == "chroniqueur") { ?> 
         
              <!-- RESULTAT CHRONIQEUR -->
              <div class="tab-pane fade in active" id="themes">&nbsp;
              	<table class="table table-striped" style="margin:0 auto;">
              		<tr>
              			<th>N°</th>
              			<th>Nom</th>
              			<th>Prénom</th>
              			<th>Login</th>
              			<th>E-mail</th>
              			<th>Téléphone</th>
              			<th>Depuis le</th>
              			<th>Actions</th>
              		</tr>
              		<?php 
						foreach ($this->search as $c) {
							$color = ($c->valid == 1 ? "class='green bold'" : "class='red2 bold'");
							echo'<tr>
		  							<td><span '.$color.'>'.$c->id.'</span></td>
		  							<td>'.$c->nom.'</td>
		  							<td>'.$c->prenom.'</td>
		  							<td>'.$c->pseudo.'</td>
		  							<td>'.$c->email.'</td>
		  							<td>'.$c->tel.'</td>
		  							<td>'.$c->date_inscription.'</td>
		  							<td>
										<div class="btn-group">
										  <a class="btn btn-primary" data-toggle="dropdown" href="#"><i class="icon-user icon-white"></i> Action</a>
										  <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
										  <ul class="dropdown-menu">
										    <li><a href="#" class="contact" title="'.$c->email.'"><i class="i  icon-envelope"></i> &nbsp;Contacter</a></li>
										    <li><a href="'.$this->baseUrl('admin/edit/idk/'.$c->id).'"><i class="icon-pencil"></i>  &nbsp;Modifier</a></li>
										    <li><a href="#" class="diff-kr" title="'.$c->valid.'&&'.$c->pseudo.'&&'.$c->id.'"><i class="icon-ban-circle"></i>  &nbsp;Bannir</a></li>
										    <li class="divider"></li>
										    <li><a href="'.$this->baseUrl('admin/search/idk/'.$c->id).'"><i class="i icon-briefcase"></i>  &nbsp;Chroniques</a></li>
										  </ul>
										</div>
									</td>
								</tr>
	  						';
						}
              		?>
              	</table>
              	<br />
              </div>
              
              <?php }elseif ($this->type == "lecteur") { ?> 
         
              <!-- RESULTAT LECTEUR -->
              <div class="tab-pane fade in active" id="themes">&nbsp;
              	<table class="table table-striped" style="margin:0 auto;">
              		<tr>
              			<th>Nom</th>
              			<th>Prénom</th>
              			<th>Login</th>
              			<th>E-mail</th>
              			<th>Depuis le</th>
              			<th>Actions</th>
              		</tr>
              		<?php 
              			foreach ($this->search as $l) {
							
              				$color = ($l->valid == 1 ? "class='green bold'" : "class='red2 bold'");
							echo'<tr>
		  							<td>'.$l->nom.'</td>
		  							<td>'.$l->prenom.'</td>
		  							<td><span '.$color.'>'.$l->pseudo.'</span></td>
		  							<td>'.$l->email.'</td>
		  							<td>'.$l->date_inscription.'</td>
		  							<td>
										<div class="btn-group">
										  <a class="btn btn-primary" data-toggle="dropdown" href="#"><i class="icon-user icon-white"></i> Action</a>
										  <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
										  <ul class="dropdown-menu">
										    <li><a href="'.$this->baseUrl('admin/edit/idl/'.$l->id).'"><i class="icon-pencil"></i>  &nbsp;Modifier</a></li>
										    <li><a href="#" class="diff-lc" title="'.$l->valid.'&&'.$l->pseudo.'&&'.$l->id.'"><i class="icon-ban-circle"></i>  &nbsp;Bannir</a></li>
										    <li class="divider"></li>
										    <li><a href="#" class="details"><i class="i icon-info-sign"></i>  &nbsp;Détails<span class="nee none"><strong>Né(e) le :</strong> '.' '.$l->jour.'/'.$l->mois.'/'.$l->annee.' '.' '.$l->sexe.'</span><span class="conx none"><strong>Connexion :</strong> '.' '.$l->date_connexion.'</span><span class="none insc"><strong>Inscription :</strong> '.' '.$l->date_inscription.'</span><span class="none nom"><strong>Nom :</strong>'.' '.$l->nom.' '.$l->prenom.'</span><span class="none pseudo"><strong>Login : </strong>'.' '.$l->pseudo.'</span></a></li>
										  </ul>
										</div>
									</td>
								</tr>
	  						';
						}
              		?>
              	</table>
              	<br />
              </div>
	<?php } ?>
            
</div>
      
     &nbsp;  
     
     <!-- ------------------------ -->
     <!--  IFRAME AFFICHAGE SITE  -->
	     <div class="none" id="iframe" title="Aperçu Chronique : "><br/>
	     	<iframe name="SiteWeb" SRC="http://localhost:8888/CHRONIQUE-TIME/public/index/chronique" scrolling="yes" height="850" width="1024" FRAMEBORDER="no"></iframe>
	     </div>
     <!-- ------------------------ -->
     <!-- MODIF -OK- CHRONIQUE --- -->
     <div class="none" id="ChMd" title="Modification réussie "><br/>
     	<p style="margin:0; text-align:center;">La modification de la chronique a bien été éffectuée !</p>
     </div>
     <!-- ------------------------ -->
     <!-- MODIF -OK- THEME --- -->
     <div class="none" id="ThMd" title="Modification réussie "><br/>
     	<p style="margin:0; text-align:center;">La modification du thème a bien été éffectuée !</p>
     </div>
     <!-- ------------------------ -->
     <!-- SUPPRIMER ---- ALL ----- -->
     <div class="none" id="ThDl" title="Suppression "><br/>
     	<p style="margin:0; text-align:center;">Êtes vous sûre de vouloir supprimer <br /> <span class="supp-txt"></span> <br /> ?</p>
     </div>
     <!-- ------------------------ -->
     
     <!-- DIFFUSION --- PAGE ----- -->
     <div class="none" id="PgDf" title="Diffusion "><br/>
     	<p style="margin:0; text-align:center;">Souhaitez vous changer la diffusion de l'article <br /> <span class="diff-txt"></span> <br /> ?</p>
     </div>
     <!-- ------------------------ -->
     
     <!-- RECHERCHE ECHEC  ------- -->
     <div class="none" id="EcRc" title="Échec Recherche "><br/>
     	<p style="margin:0; text-align:center;">La recherche n'a retournée aucun résultat correspondant au mots clé !</p>
     </div>
     <!-- ------------------------ -->
     
     <!-- RECHERCHE CHRONIK ----- -->
     <div class="none" id="ChRc" title="Recherche Chronique "><br/>
     	<p style="margin:0; text-align:center;"><?php echo $this->formc; ?></p>
     </div>
     <!-- ------------------------ -->
     
     <!-- RECHERCHE THEME ------- -->
     <div class="none" id="ThRc" title="Recherche Thème "><br/>
     	<p style="margin:0; text-align:center;"><?php echo $this->formt; ?></p>
     </div>
     <!-- ------------------------ -->
     
      <!-- RECHERCHE CHRONKR ----- -->
     <div class="none" id="ChRk" title="Recherche Chroniqueur "><br/>
     <p style="margin:0; text-align:center;"><?php echo $this->formk; ?></p>
     </div>
     <!-- ----------------------- -->
      
      <!-- RECHERCHE PAGES ----- -->
     <div class="none" id="PgRc" title="Recherche Page "><br/>
     	<p style="margin:0; text-align:center;"><?php echo $this->formp; ?></p>
     </div>
     <!-- ------------------------ -->
     
      <!-- RECHERCHE LCTR ------- -->
     <div class="none" id="LcRc" title="Recherche Lecteur "><br/>
     <p style="margin:0; text-align:center;"><?php echo $this->forml; ?></p>
     </div>
     <!-- ------------------------ -->
     
     <!-- DIFFUSION --- PAGE ----- -->
     <div class="none" id="PgDf" title="Diffusion "><br/>
     	<p style="margin:0; text-align:center;">Souhaitez vous changer la diffusion de l'article <br /> <span class="diff-txt"></span> <br /> ?</p>
     </div>
     <!-- ------------------------ -->
     
     <!-- ------------------------ -->  
     <!--  MODIF  -OK- PAGE  ----- -->
     <div class="none" id="PgMd" title="Modification réussie "><br/>
     	<p style="margin:0; text-align:center;">La modification de la page a bien été éffectuée !</p>
     </div>
     <!-- ------------------------ -->
     
</div>