<script>
<!-- 
	
	$('#myTab a').click(function(e) {
	  e.preventDefault();
	  $(this).tab('show');
	});

	$('#myTab a[href="#chroniqueurs"]').tab('show'); // Select tab by name
	$('#myTab a:first').tab('show'); // Select first tab
	$('#myTab a:last').tab('show'); // Select last tab
	$('#myTab li:eq(2) a').tab('show'); // Select third tab (0-indexed)

	$(".element").live('click',function(){

		$(this).popover({

			animation : true,
			placement : 'top',
			trigger   : 'click',
			title	  : 'Info Chronique :',
			content : 'Thème : Famille Visite : 128 Pages : 5 Commentaires : 34 Abus : 0 Note : 4',
			delay : { show: 500, hide: 100 }
		 
		});
		$(this).popover('show');
		
	});

	//Dialog Formulaires d'ajout
	$("#inscC").live('click',function() {

	   $( "#NwCh" ).dialog({
	      resizable: false,
	      width: 500,
	      height:550,
	      modal: true
	   });
	   
	});
	$("#inscL").live('click',function() {

	   $( "#NwLc" ).dialog({
	      resizable: false,
	      width: 500,
	      height:550,
	      modal: true
	   });
	   
	});

	//Msg de confirmation de diffusion
	$(".diff-kr").live('click',function() {

	   var clas = $(this).attr('class').split(' ');
	   var info = $(this).attr('title').split('&&');
	   var valid = info['0'];
	   var name = info['1'];
	   var id = info['2'];
	   var x = 'kr/id/'+id+'/vl/'+valid;

	   $('#KrDf .diff-txt').html('"'+name+'"');
	   $( "#KrDf" ).dialog({
	      resizable: false,
	      width: 360,
	      height:200,
	      modal: true,
	      buttons: {  
		      Permuter: function() { window.location.replace("<?php echo $this->baseUrl('admin/diff/cat/');?>"+x);  } , 
		      Annuler: function() { $( this ).dialog( "close" ); }  
	      }
	   });
	   $('.ui-dialog-buttons .ui-dialog-buttonpane button').attr('class','btn');
	   
	});
	$(".diff-lc").live('click',function() {

		   var clas = $(this).attr('class').split(' ');
		   var info = $(this).attr('title').split('&&');
		   var valid = info['0'];
		   var name = info['1'];
		   var id = info['2'];
		   var x = 'lc/id/'+id+'/vl/'+valid;

		   $('#LcDf .diff-txt').html('"'+name+'"');
		   $( "#LcDf" ).dialog({
		      resizable: false,
		      width: 360,
		      height:200,
		      modal: true,
		      buttons: {  
			      Permuter: function() { window.location.replace("<?php echo $this->baseUrl('admin/diff/cat/');?>"+x);  } , 
			      Annuler: function() { $( this ).dialog( "close" ); }  
		      }
		   });
		   $('.ui-dialog-buttons .ui-dialog-buttonpane button').attr('class','btn');
		   
		});

	//Msg de confirmation de suppression
	$(".supp-kr").live('click',function() {

	   var info = $(this).attr('title').split('&&');
	   var name = info['0'];
	   var id = info['1'];
	   var x = 'supp-us/id/'+id;

	   $('#KrSp .supp-txt').html('"'+name+'"');
	   $( "#KrSp" ).dialog({
	      resizable: false,
	      width: 360,
	      height:200,
	      modal: true,
	      buttons: {  
		 	  Confirmer: function() { window.location.replace("<?php echo $this->baseUrl('admin/del/cat/');?>"+x);  } , 
		      Annuler: function() { $( this ).dialog( "close" ); }  
	      }
	   });
	   $('.ui-dialog-buttons .ui-dialog-buttonpane button').attr('class','btn');
	   
	});
	$(".supp-lc").live('click',function() {

		   var info = $(this).attr('title').split('&&');
		   var name = info['0'];
		   var id = info['1'];
		   var x = 'supp-us/id/'+id;

		   $('#LcSp .supp-txt').html('"'+name+'"');
		   $( "#LcSp" ).dialog({
		      resizable: false,
		      width: 360,
		      height:200,
		      modal: true,
		      buttons: {  
			   	  Confirmer: function() { window.location.replace("<?php echo $this->baseUrl('admin/del/cat/');?>"+x);  } , 
			      Annuler: function() { $( this ).dialog( "close" ); }  
		      }
		   });
		   $('.ui-dialog-buttons .ui-dialog-buttonpane button').attr('class','btn');
		   
	});
	$(".supp-ad").live('click',function() {

		   var info = $(this).attr('title').split('&&');
		   var name = info['0'];
		   var id = info['1'];
		   var x = 'supp-ad/id/'+id;

		   $('#AdSp .supp-txt').html('"'+name+'"');
		   $( "#AdSp" ).dialog({
		      resizable: false,
		      width: 360,
		      height:200,
		      modal: true,
		      buttons: {  
			      Confirmer: function() { window.location.replace("<?php echo $this->baseUrl('admin/del/cat/');?>"+x);  } , 
			      Annuler: function() { $( this ).dialog( "close" ); }  
		      }
		   });
		   $('.ui-dialog-buttons .ui-dialog-buttonpane button').attr('class','btn');
		   
		});

	
	//Contact Mail
	$(".contact").live('click',function() {

	   var clas = $(this).attr('class').split(' ');
	   var mail = $(this).attr('title');

	   $("textarea#texte").markItUp(mySettings);
	   $('#Mail #email').val(mail);
	   $( "#Mail" ).dialog({
	      resizable: false,
	      width: 750,
	      height:670,
	      resizable: true,
	      show: "fade",
	      option: "hide",
	      hide: "explode",
	      modal: true,
	      buttons: {  
		      Annuler: function() { $( this ).dialog( "close" ); }  
	      }
	   });
	   $('.ui-dialog-buttons .ui-dialog-buttonpane button').attr('class','btn');
	   
	});
	
	//Modal Details
	$(".details").live('click',function() {

		var birth = $('.nee',this).html();
		var conx = $('.conx',this).html();
		var insc = $('.insc',this).html();
		var nom = $('.nom',this).html();
		var pseudo = $('.pseudo',this).html();
		var tel = $('.tel',this).html();
		var mail = $('.mail',this).html();

		$('#myModal .modal-name').html(nom);
		$('#myModal .modal-pseudo').html(pseudo);
		$('#myModal .modal-birth').html(birth);
		$('#myModal .modal-tel').html(tel);
		$('#myModal .modal-mail').html(mail);
		$('#myModal .modal-datei').html(insc);
		$('#myModal .modal-dated').html(conx);

		
		$('#myModal').modal({
			backdrop: true,
		      modal: false,
			keyboard: true
		});
	});


	//Form de recherche
	$("#Rchc").live('click',function() {

	   $( "#ChRc" ).dialog({
	      resizable: false,
	      width: 360,
	      height:270,
	      modal: true,
	      buttons: {  
		      Annuler: function() { $( this ).dialog( "close" ); }  
	      }
	   });
	   $('.ui-dialog-buttons .ui-dialog-buttonpane button').attr('class','btn');
	   
	});
	$("#Rchl").live('click',function() {

	   $( "#ThRc" ).dialog({
	      resizable: false,
	      width: 360,
	      height:270,
	      modal: true,
	      buttons: {  
		      Annuler: function() { $( this ).dialog( "close" ); }  
	      }
	   });
	   $('.ui-dialog-buttons .ui-dialog-buttonpane button').attr('class','btn');
	   
	});

// --> 
</script>


<div id="wrapper">
  	<div class="bs-docs-example">
            <ul id="myTab" class="nav nav-tabs">
              <li class="active"><a href="#chroniqueurs" data-toggle="tab">Chroniqueurs</a></li>
              <li><a href="#lecteurs" data-toggle="tab">Lecteurs</a></li>
              <li><a href="#admin" data-toggle="tab">Administrateurs</a></li>
               <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Rechercher <b class="caret"></b></a>
                <ul class="dropdown-menu" style="width:150px;">
                  <li><a href="#" data-toggle="tab" id="Rchc">Chroniqueur</a></li>
                  <li><a href="#" data-toggle="tab" id="Rchl">Lecteur</a></li>
                  <li><a href="#" data-toggle="tab" id="Rcha">Admin</a></li>
                </ul>
               </li>
               <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Inscrire <b class="caret"></b></a>
                <ul class="dropdown-menu" style="width:123px;">
                  <li><a href="#" id="inscC" data-toggle="tab">Chroniqueur</a></li>
                  <li><a href="#" id="inscL" data-toggle="tab">Lecteur</a></li>
                  <li><a href="#" id="inscA" data-toggle="tab">Admin</a></li>
                </ul>
              </li>
            </ul>
            <?php echo $this->message; ?>
            <div id="myTabContent" class="tab-content">
            
              <!-- ONGLET CHRONIQUEURS -->
              <div class="tab-pane fade in active" id="chroniqueurs">&nbsp;
              	<table class="table table-striped">
              		<caption><i>Les Éditeurs de ChroniqueTime</i></caption>
              		<tr>
              			<th>N°</th>
              			<th>Pseudo</th>
              			<th>E-mail</th>
              			<th>Téléphone</th>
              			<th>Depuis le</th>
              			<th>Actions</th>
              		</tr>
              		<?php 
              			foreach ($this->chroniqueurs as $c) {
							$color = ($c->valid == 1 ? "class='green bold'" : "class='red2 bold'");
							echo'<tr>
		  							<td>'.$c->id.'</td>
		  							<td><span '.$color.'>'.$c->pseudo.'</span></td>
		  							<td>'.$c->email.'</td>
		  							<td>'.$c->tel.'</td>
		  							<td>'.$c->date_inscription.'</td>
		  							<td>
										<div class="btn-group">
										  <a class="btn btn-primary" data-toggle="dropdown" href="#"><i class="icon-user icon-white"></i> Action</a>
										  <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
										  <ul class="dropdown-menu">
										    <li><a href="#" class="contact" title="'.$c->email.'"><i class="i  icon-envelope"></i> &nbsp;Contacter</a></li>
										    <li><a href="'.$this->baseUrl('admin/edit/idk/'.$c->id).'"><i class="icon-pencil"></i>  &nbsp;Modifier</a></li>
										    <li><a href="#" class="diff-kr" title="'.$c->valid.'&&'.$c->pseudo.'&&'.$c->id.'"><i class="icon-ban-circle"></i>  &nbsp;Bannir</a></li>
										    <li><a href="#" class="supp-kr" title="'.$c->pseudo.'&&'.$c->id.'"><i class="icon-trash"></i>  &nbsp;Supprimer</a></li>
										    <li class="divider"></li>
										    <li><a href="'.$this->baseUrl('admin/search/idk/'.$c->id).'"><i class="i icon-briefcase"></i>  &nbsp;Chroniques</a></li>
											<li><a href="#" class="details"><i class="i icon-info-sign"></i>  &nbsp;Détails<span class="nee none"><strong>Né(e) le :</strong> '.' '.$c->jour.'/'.$c->mois.'/'.$c->annee.' '.' '.$c->sexe.'</span><span class="conx none"><strong>Connexion :</strong> '.' '.$c->date_connexion.'</span><span class="none insc"><strong>Inscription :</strong> '.' '.$c->date_inscription.'</span><span class="none tel"><strong>Téléphone :</strong> '.' '.$c->tel.'</span><span class="none nom"><strong>Nom :</strong>'.' '.$c->nom.' '.$c->prenom.'</span><span class="none pseudo"><strong>Pseudo : </strong>'.' '.$c->pseudo.'</span><span class="none mail"><strong>E-mail : </strong>'.' '.$c->email.'</span></a></li>
										  </ul>
										</div>
									</td>
								</tr>
	  						';
						}
              		?>
              	</table>
              </div>
              
              <!-- ONGLET LECTEURS -->
              <div class="tab-pane fade" id="lecteurs">&nbsp;
              	<table class="table table-striped">
              		<caption><i>Les Lecteurs de nos chroniques</i></caption>
              		<tr>
              			<th>Nom</th>
              			<th>Prénom</th>
              			<th>Pseudo</th>
              			<th>E-mail</th>
              			<th>Depuis le</th>
              			<th>Actions</th>
              		</tr>
              		<?php 
              			foreach ($this->lecteurs as $l) {
							
              				$color = ($l->valid == 1 ? "class='green bold'" : "class='red2 bold'");
							echo'<tr>
		  							<td>'.$l->nom.'</td>
		  							<td>'.$l->prenom.'</td>
		  							<td><span '.$color.'>'.$l->pseudo.'</span></td>
		  							<td>'.$l->email.'</td>
		  							<td>'.$l->date_inscription.'</td>
		  							<td>
										<div class="btn-group">
										  <a class="btn btn-primary" data-toggle="dropdown" href="#"><i class="icon-user icon-white"></i> Action</a>
										  <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
										  <ul class="dropdown-menu">
										    <li><a href="'.$this->baseUrl('admin/edit/idl/'.$l->id).'"><i class="icon-pencil"></i>  &nbsp;Modifier</a></li>
										    <li><a href="#" class="diff-lc" title="'.$l->valid.'&&'.$l->pseudo.'&&'.$l->id.'"><i class="icon-ban-circle"></i>  &nbsp;Bannir</a></li>
										      <li><a href="#" class="supp-lc" title="'.$l->pseudo.'&&'.$l->id.'"><i class="icon-trash"></i>  &nbsp;Supprimer</a></li>
										 	  <li class="divider"></li>
										    <li><a href="#" class="details"><i class="i icon-info-sign"></i>  &nbsp;Détails<span class="nee none"><strong>Né(e) le :</strong> '.' '.$l->jour.'/'.$l->mois.'/'.$l->annee.' '.' '.$l->sexe.'</span><span class="conx none"><strong>Connexion :</strong> '.' '.$l->date_connexion.'</span><span class="none insc"><strong>Inscription :</strong> '.' '.$l->date_inscription.'</span><span class="none nom"><strong>Nom :</strong>'.' '.$l->nom.' '.$l->prenom.'</span><span class="none pseudo"><strong>Pseudo : </strong>'.' '.$l->pseudo.'</span><span class="none mail"><strong>E-Mail : </strong>'.' '.$l->email.'</span></a></li>
										  </ul>
										</div>
									</td>
								</tr>
	  						';
						}
              		?>
              	</table>
              </div>
              
              <!-- ONGLET ADMIN -->
              <div class="tab-pane fade" id="admin">&nbsp;
              	<table class="table table-striped">
              		<caption><i>Les Administrateurs de ChroniqueTime</i></caption>
              		<tr>
              			<th>Id</th>
              			<th>Prénom</th>
              			<th>E-mail</th>
              			<th>Depuis le</th>
              			<th>Connecté le</th>
              			<th>Actions</th>
              		</tr>
              		<?php 
              			foreach ($this->admin as $a) {
				
							echo'<tr>
		  							<td>'.$a->id.'</td>
		  							<td>'.$a->prenom.'</td>
		  							<td>'.$a->email.'</td>
		  							<td>'.$a->date_creation.'</td>
		  							<td>'.$a->date_connexion.'</td>
		  							<td>
										<div class="btn-group">
										  <a class="btn btn-primary" data-toggle="dropdown" href="#"><i class="icon-user icon-white"></i> Action</a>
										  <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
										  <ul class="dropdown-menu">
										    <li><a href="#"><i class="icon-pencil"></i> Editer</a></li>
										    <li><a href="#"><i class="icon-ban-circle"></i> Bannir</a></li>
										    <li><a href="#" class="supp-ad" title="'.$a->prenom.'&&'.$a->id.'"><i class="icon-trash"></i>  &nbsp;Supprimer</a></li>
										  </ul>
										</div>
									</td>
								</tr>
	  						';
						}
              		?>
              	</table>
              </div>
              
            </div>
            
  	</div>
      
     &nbsp;  
          
</div>

	 <!----- FORM NEW CHRONIQUEUR ----->
	     <div class="none" id="NwCh" title="Nouveau Chroniqueur : "><br/>
	     	<?php echo $this->newChroniqueur; ?>
	     </div>
     <!-- -------------------------- -->

	 <!-- AJOUT -OK- NEW CHRONIQUEUR -->
	     <div class="none" id="ChOk" title="Ajout réussi "><br/>
	     	<p style="margin:0; text-align:center;">Un nouveau chroniqueur viens d'être ajouté !</p>
	     </div>
     <!-- -------------------------- -->
     <!-- MODIF -OK- CHRONIQUEUR --- -->
     <div class="none" id="ChMd" title="Modification réussie "><br/>
     	<p style="margin:0; text-align:center;">La modification de l'utilisateur a bien été éffectuée !</p>
     </div>
     <!-- -------------------------- -->
     
     
	 <!----- FORM NEW LECTEUR  -------->
	     <div class="none" id="NwLc" title="Nouveau Lecteur : "><br/>
	     	<?php echo $this->newLecteur; ?>
	     </div>
     <!-- -------------------------- -->

	 <!-- AJOUT -OK- NEW LECTEUR ------>
	     <div class="none" id="LcOk" title="Ajout réussi "><br/>
	     	<p style="margin:0; text-align:center;">Un nouveau lecteur viens d'être ajouté !</p>
	     </div>
     <!-- -------------------------- -->
     <!-- MODIF -OK- LECTEUR ------- -->
     <div class="none" id="LcMd" title="Modification réussie "><br/>
     	<p style="margin:0; text-align:center;">La modification de l'utilisateur a bien été éffectuée !</p>
     </div>
     <!-- -------------------------- -->
     
     <!-- DIFFUSION -- CHRONKR ----- -->
     <div class="none" id="KrDf" title="Bannir "><br/>
     	<p style="margin:0; text-align:center;">Souhaitez vous changer l'etat de ce chroniqueur<br /> <span class="diff-txt"></span> <br /> ?</p>
     </div>
     <!-- ------------------------ -->
     <!-- DIFFUSION -- LECTR ----- -->
     <div class="none" id="LcDf" title="Bannir "><br/>
     	<p style="margin:0; text-align:center;">Souhaitez vous changer l'etat de ce lecteur<br /> <span class="diff-txt"></span> <br /> ?</p>
     </div>
     <!-- ------------------------ -->
     <!-- SUPPRESSION --- LECTR -- -->
     <div class="none" id="LcSp" title="Supprimer "><br/>
     	<p style="margin:0; text-align:center;">Souhaitez vous supprimer le lecteur<br /> <span class="supp-txt"></span> <br /> ?</p>
     </div>
     <!-- ------------------------ -->
     <!-- SUPPRESSION --- CHRNK -- -->
     <div class="none" id="KrSp" title="Supprimer "><br/>
     	<p style="margin:0; text-align:center;">Souhaitez vous supprimer le chroniquer<br /> <span class="supp-txt"></span> <br /> ?</p>
     </div>
     <!-- ------------------------ -->
     <!-- SUPPRESSION --- ADMIN -- -->
     <div class="none" id="AdSp" title="Supprimer "><br/>
     	<p style="margin:0; text-align:center;">Souhaitez vous supprimer l'administrateur<br /> <span class="supp-txt"></span> <br /> ?</p>
     </div>
     <!-- ------------------------ -->
     
     <!-- CONTACTER UTILISATEUR -- -->
     <div class="none" id="Mail" title="Contacter par mail : "><br/>
     	<p style="margin:0; text-align:center;"><?php echo $this->formMail; ?></p>
     </div>
     <!-- ------------------------ -->
     <!-- CONTACT OK UTILISATEUR - -->
     <div class="none" id="MlOk" title="Message envoyé "><br/>
     	<p style="margin:0; text-align:center;">Votre mail a bien été transmis à l'utilisateur !</p>
     </div>
     <!-- ------------------------ -->
     
     <!-- DETAILS myMODAL USERS  -->
     <div id="myModal" class="modal hide fade none" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Détails de l'utilisateur : </h3>
	  </div>
	  <div class="modal-body">
	    <p class="modal-name"></p>
	    <p class="modal-pseudo"></p>
	    <p class="modal-birth"></p>
	    <p class="modal-mail"></p>
	    <p class="modal-tel"></p>
	    <br />
	    <p class="modal-datei"></p>
	    <p class="modal-dated"></p>
	  </div>
	  <div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Fermer</button>
	  </div>
	</div>
    <!-- ------------------------ -->
    
    
     <!-- ECHEC FORM ----- -->
     <div class="none" id="Err00" title="Echec de Formulaire "><br/>
     <p style="margin:0; text-align:center;">Le formulaire n'a pas été correctement saisi, veuillez bien respecter les champs et leur type !</p>
     </div>
     <!-- ----------------------- -->
     
     <!-- ECHEC EMAIL ----- -->
     <div class="none" id="Err01" title="Echec E-mail  "><br/>
     <p style="margin:0; text-align:center;">Le mail saisi est déjà utilisé par un utilisateur.</p>
     </div>
     <!-- ----------------------- -->
     
     <!-- RECHERCHE CHRONKR ----- -->
     <div class="none" id="ChRc" title="Recherche Chroniqueur "><br/>
     <p style="margin:0; text-align:center;"><?php echo $this->formk; ?></p>
     </div>
     <!-- ----------------------- -->
     
      <!-- RECHERCHE LCTR ------- -->
     <div class="none" id="ThRl" title="Recherche Lecteur "><br/>
     <p style="margin:0; text-align:center;"><?php echo $this->forml; ?></p>
     </div>
     <!-- ------------------------ -->